DROP TABLE t_sk_bairro CASCADE CONSTRAINTS;

DROP TABLE t_sk_cidade CASCADE CONSTRAINTS;

DROP TABLE t_sk_colaborador CASCADE CONSTRAINTS;

DROP TABLE t_sk_colaborador_endereco CASCADE CONSTRAINTS;

DROP TABLE t_sk_colaborador_projeto CASCADE CONSTRAINTS;

DROP TABLE t_sk_departamento CASCADE CONSTRAINTS;

DROP TABLE t_sk_endereco CASCADE CONSTRAINTS;

DROP TABLE t_sk_estado CASCADE CONSTRAINTS;

DROP TABLE t_sk_projeto CASCADE CONSTRAINTS;

DROP TABLE t_sk_telefone CASCADE CONSTRAINTS;

DROP TABLE t_sk_telefone_colaborador CASCADE CONSTRAINTS;

DROP TABLE t_sk_tipo_endereco CASCADE CONSTRAINTS;

DROP TABLE t_sk_tipo_logradouro CASCADE CONSTRAINTS;